# Form implementation generated from reading ui file 'f:\Code\projects\python_projects\GeneticAlgorithmUniversityClassScheduler\qt_ui\generating.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtWidgets


class Ui_Generating(object):
    def setupUi(self, Generating):
        Generating.setObjectName("Generating")
        Generating.resize(396, 116)
        Generating.setMinimumSize(QtCore.QSize(396, 116))
        Generating.setMaximumSize(QtCore.QSize(396, 116))
        Generating.setWindowFlags(
            Generating.windowFlags() & ~QtCore.Qt.WindowType.WindowCloseButtonHint
        )
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Generating)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(
            20,
            40,
            QtWidgets.QSizePolicy.Policy.Minimum,
            QtWidgets.QSizePolicy.Policy.Expanding,
        )
        self.verticalLayout.addItem(spacerItem)
        self.label = QtWidgets.QLabel(parent=Generating)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        spacerItem1 = QtWidgets.QSpacerItem(
            20,
            40,
            QtWidgets.QSizePolicy.Policy.Minimum,
            QtWidgets.QSizePolicy.Policy.Expanding,
        )
        self.verticalLayout.addItem(spacerItem1)
        self.progressBar = QtWidgets.QProgressBar(parent=Generating)
        self.progressBar.setMaximum(0)
        self.progressBar.setProperty("value", -1)
        self.progressBar.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setFormat("")
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout.addWidget(self.progressBar)
        spacerItem2 = QtWidgets.QSpacerItem(
            20,
            40,
            QtWidgets.QSizePolicy.Policy.Minimum,
            QtWidgets.QSizePolicy.Policy.Expanding,
        )
        self.verticalLayout.addItem(spacerItem2)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(Generating)
        QtCore.QMetaObject.connectSlotsByName(Generating)

    def retranslateUi(self, Generating):
        _translate = QtCore.QCoreApplication.translate
        Generating.setWindowTitle(_translate("Generating", "Generating"))
        self.label.setText(_translate("Generating", "Generating..."))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Generating = QtWidgets.QWidget()
    ui = Ui_Generating()
    ui.setupUi(Generating)
    Generating.show()
    sys.exit(app.exec())
