# Form implementation generated from reading ui file 'f:\Code\projects\python_projects\GeneticAlgorithmUniversityClassScheduler\qt_ui\subject.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(716, 553)
        Dialog.setMinimumSize(QtCore.QSize(716, 553))
        Dialog.setMaximumSize(QtCore.QSize(716, 553))
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSizeConstraint(
            QtWidgets.QLayout.SizeConstraint.SetMinimumSize
        )
        self.gridLayout.setObjectName("gridLayout")
        self.lblDesc = QtWidgets.QLabel(parent=Dialog)
        self.lblDesc.setObjectName("lblDesc")
        self.gridLayout.addWidget(self.lblDesc, 1, 3, 1, 1)
        self.lblCode = QtWidgets.QLabel(parent=Dialog)
        self.lblCode.setObjectName("lblCode")
        self.gridLayout.addWidget(self.lblCode, 1, 0, 1, 1)
        self.lineEditCode = QtWidgets.QLineEdit(parent=Dialog)
        self.lineEditCode.setObjectName("lineEditCode")
        self.gridLayout.addWidget(self.lineEditCode, 1, 1, 1, 1)
        self.lineEditName = QtWidgets.QLineEdit(parent=Dialog)
        self.lineEditName.setObjectName("lineEditName")
        self.gridLayout.addWidget(self.lineEditName, 0, 1, 1, 1)
        self.lblHours = QtWidgets.QLabel(parent=Dialog)
        self.lblHours.setObjectName("lblHours")
        self.gridLayout.addWidget(self.lblHours, 0, 3, 1, 1)
        self.lineEditHours = QtWidgets.QLineEdit(parent=Dialog)
        self.lineEditHours.setObjectName("lineEditHours")
        self.gridLayout.addWidget(self.lineEditHours, 0, 4, 1, 1)
        self.lblName = QtWidgets.QLabel(parent=Dialog)
        self.lblName.setObjectName("lblName")
        self.gridLayout.addWidget(self.lblName, 0, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.radioLec = QtWidgets.QRadioButton(parent=Dialog)
        self.radioLec.setObjectName("radioLec")
        self.horizontalLayout_4.addWidget(self.radioLec)
        self.radioLab = QtWidgets.QRadioButton(parent=Dialog)
        self.radioLab.setObjectName("radioLab")
        self.horizontalLayout_4.addWidget(self.radioLab)
        self.gridLayout.addLayout(self.horizontalLayout_4, 1, 4, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.treeSchedule = QtWidgets.QTreeView(parent=Dialog)
        self.treeSchedule.setObjectName("treeSchedule")
        self.verticalLayout.addWidget(self.treeSchedule)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnFinish = QtWidgets.QPushButton(parent=Dialog)
        self.btnFinish.setObjectName("btnFinish")
        self.horizontalLayout.addWidget(self.btnFinish)
        self.btnCancel = QtWidgets.QPushButton(parent=Dialog)
        self.btnCancel.setObjectName("btnCancel")
        self.horizontalLayout.addWidget(self.btnCancel)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Subject"))
        self.lblDesc.setText(_translate("Dialog", "Type"))
        self.lblCode.setText(_translate("Dialog", "Code"))
        self.lblHours.setText(_translate("Dialog", "Hours/Week"))
        self.lblName.setText(_translate("Dialog", "Name"))
        self.radioLec.setText(_translate("Dialog", "Lecture"))
        self.radioLab.setText(_translate("Dialog", "Laboratory"))
        self.btnFinish.setText(_translate("Dialog", "Finish"))
        self.btnCancel.setText(_translate("Dialog", "Cancel"))
